```{r, results="asis"}
# Define variable weight containing the weight column of datTrait
Tissue.Time <- as.data.frame(phenotype$Tissue.Time);
names(Tissue.Time) <- "Tissue.Time"

# names (colors) of the modules
modNames <- substring(names(MEs), 1)
geneModuleMembership <- as.data.frame(cor(log.tdata.FPKM.subset, MEs, use = "p"));
MMPvalue <- as.data.frame(corPvalueStudent(as.matrix(geneModuleMembership), nSamples));

names(geneModuleMembership) <- paste("MM", modNames, sep="");
names(MMPvalue) <- paste("p.MM", modNames, sep="");
geneTraitSignificance = as.data.frame(cor(log.tdata.FPKM.subset, Tissue.Time, use = "p"));
GSPvalue <- as.data.frame(corPvalueStudent(as.matrix(geneTraitSignificance), nSamples));
names(geneTraitSignificance) <- paste("GS.", names(Tissue.Time), sep="");
names(GSPvalue) <- paste("p.GS.", names(Tissue.Time), sep="");                 
```

```{r, results="asis"}
modulename <- modNames

for(i in 1:length(modulename)){
  module <- modulename[i]
    cat("###", modulename[i],"\n")
    print(htmltools::tagList(MMvGS(module, geneModuleMembership, geneTraitSignificance, MEs)))
    cat("\n \n")
}
```

```{r}
p <- plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
p
```