##Scree plot and summary statistics
```{r PCA tissue.2DG.96hr log scree}
tdata.FPKM.sample.info <- readRDS(here("Data","20190406_RNAseq_B6_4wk_2DG_counts_phenotypes.RData"))

tdata.FPKM.sample.info.tissue.2DG.96hr <- rownames_to_column(tdata.FPKM.sample.info) %>% filter(Treatment=="2DG" & Time=="96 hrs") %>% column_to_rownames('rowname')

tdata.FPKM <- readRDS(here("Data","20190406_RNAseq_B6_4wk_2DG_counts_numeric.RData"))

log.tdata.FPKM <- log(tdata.FPKM + 1)
log.tdata.FPKM <- as.data.frame(log.tdata.FPKM)

rows <- rownames(tdata.FPKM.sample.info.tissue.2DG.96hr)

log.tdata.FPKM.tissue.2DG.96hr <- rownames_to_column(log.tdata.FPKM) 

log.tdata.FPKM.tissue.2DG.96hr <- log.tdata.FPKM.tissue.2DG.96hr %>% filter(rowname %in% rows) %>% column_to_rownames('rowname')

pca <- prcomp(log.tdata.FPKM.tissue.2DG.96hr, center = T)

screeplot(pca,type = "lines")

summary(pca)
```

##Tissue
```{r PCA tissue.2DG.96hr log}
Tissue_color <- as.factor(tdata.FPKM.sample.info.tissue.2DG.96hr$Tissue)
Tissue_color <- as.data.frame(Tissue_color)
col_tissue <- colorRampPalette(brewer.pal(n = 12, name = "Paired"))(9)[Tissue_color$Tissue_color]
pca_tissue <- cbind(Tissue_color,pca$x[,1],pca$x[,2])
pca_tissue <- as.data.frame(pca_tissue)

p <- ggplot(pca_tissue,aes(pca$x[,1], pca$x[,2]))
p <- p + geom_point(aes(fill = as.factor(pca_tissue$Tissue_color)), shape=21, size=4) + theme_bw()
p <- p + theme(legend.title = element_text(size=10,face="bold")) + 
  theme(legend.text = element_text(size=10, face="bold"))
p <- p+ xlab("PCA 1 (39.73%)") + ylab("PCA 2 (20.63%)") + theme(axis.title = element_text(face="bold"))
p <- p + stat_ellipse(aes(pca$x[,1], pca$x[,2], group = Tissue_color, fill = as.factor(pca_tissue$Tissue_color)), geom="polygon",level=0.95,alpha=0.2) +
  scale_fill_manual(values=c("#B15928", "#F88A89", "#F06C45", "#A6CEE3", "#52AF43", "#FE870D", "#C7B699", "#569EA4","#B294C7"),name="Tissue Type",
                       breaks=c("Spleen", "Kidney","Liver","Heart","Hypothanamus","Pre-frontal Cortex","Small Intestine","Hippocampus","Skeletal Muscle"),
                       labels=c("Spleen", "kidney","Liver","Heart","Hypothalamus","Pre-frontal Cortex","Small Intestine","Hippocampus","Skeletal Muscle")) +
  scale_linetype_manual(values=c(1,2,1,2,1))
print(p)
```

##3D Tissue 2DG 96 hrs
```{r 3D tissue 2DG 96 hrs}
Tissue_color <- as.factor(tdata.FPKM.sample.info.tissue.2DG.96hr$Tissue)
Tissue_color <- as.data.frame(Tissue_color)
col_tissue <- colorRampPalette(brewer.pal(n = 12, name = "Paired"))(9)[Tissue_color$Tissue_color]
pca_tissue <- cbind(Tissue_color,pca$x[,1],pca$x[,2],pca$x[,3])
pca_tissue <- as.data.frame(pca_tissue)
rownames(pca_tissue) <- rownames(tdata.FPKM.sample.info.tissue.2DG.96hr)

p <- plot_ly(pca_tissue, x = pca_tissue$`pca$x[, 1]`, y = pca_tissue$`pca$x[, 2]`, z = pca_tissue$`pca$x[, 3]`, color = pca_tissue$Tissue_color, colors = c("#B15928", "#F88A89", "#F06C45", "#A6CEE3", "#52AF43", "#FE870D", "#C7B699", "#569EA4","#B294C7"), text = rownames(pca_tissue)) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = "PC 1 39.73%"),
                     yaxis = list(title = "PC 2 20.63%"),
                     zaxis = list(title = "PC 3 13.61%")))
p
```

# PCA (log Tissue 4wk 2DG) {.tabset .tabset-fade .tabset-pills}
##Scree plot and summary statistics
```{r PCA tissue.2DG.4wk log scree}
tdata.FPKM.sample.info <- readRDS(here("Data","20190406_RNAseq_B6_4wk_2DG_counts_phenotypes.RData"))

tdata.FPKM.sample.info.tissue.2DG.4wk <- rownames_to_column(tdata.FPKM.sample.info) %>% filter(Treatment=="2DG" & Time=="4 wks") %>% column_to_rownames('rowname')

tdata.FPKM <- readRDS(here("Data","20190406_RNAseq_B6_4wk_2DG_counts_numeric.RData"))

log.tdata.FPKM <- log(tdata.FPKM + 1)
log.tdata.FPKM <- as.data.frame(log.tdata.FPKM)

rows <- rownames(tdata.FPKM.sample.info.tissue.2DG.4wk)

log.tdata.FPKM.tissue.2DG.4wk <- rownames_to_column(log.tdata.FPKM) 

log.tdata.FPKM.tissue.2DG.4wk <- log.tdata.FPKM.tissue.2DG.4wk %>% filter(rowname %in% rows) %>% column_to_rownames('rowname')

pca <- prcomp(log.tdata.FPKM.tissue.2DG.4wk, center = T)

screeplot(pca,type = "lines")

summary(pca)
```

##Tissue
```{r PCA tissue.2DG.4wk log}
Tissue_color <- as.factor(tdata.FPKM.sample.info.tissue.2DG.4wk$Tissue)
Tissue_color <- as.data.frame(Tissue_color)
col_tissue <- colorRampPalette(brewer.pal(n = 12, name = "Paired"))(9)[Tissue_color$Tissue_color]
pca_tissue <- cbind(Tissue_color,pca$x[,1],pca$x[,2])
pca_tissue <- as.data.frame(pca_tissue)

p <- ggplot(pca_tissue,aes(pca$x[,1], pca$x[,2]))
p <- p + geom_point(aes(fill = as.factor(pca_tissue$Tissue_color)), shape=21, size=4) + theme_bw()
p <- p + theme(legend.title = element_text(size=10,face="bold")) + 
  theme(legend.text = element_text(size=10, face="bold"))
p <- p+ xlab("PCA 1 (39.14%)") + ylab("PCA 2 (19.24%)") + theme(axis.title = element_text(face="bold"))
p <- p + stat_ellipse(aes(pca$x[,1], pca$x[,2], group = Tissue_color, fill = as.factor(pca_tissue$Tissue_color)), geom="polygon",level=0.95,alpha=0.2) +
  scale_fill_manual(values=c("#B15928", "#F88A89", "#F06C45", "#A6CEE3", "#52AF43", "#FE870D", "#C7B699", "#569EA4","#B294C7"),name="Tissue Type",
                       breaks=c("Spleen", "Kidney","Liver","Heart","Hypothanamus","Pre-frontal Cortex","Small Intestine","Hippocampus","Skeletal Muscle"),
                       labels=c("Spleen", "kidney","Liver","Heart","Hypothalamus","Pre-frontal Cortex","Small Intestine","Hippocampus","Skeletal Muscle")) +
  scale_linetype_manual(values=c(1,2,1,2,1))
print(p)
```
