---
title: "B6 96hr and 4WK 2DG"
author: Ann Wells
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    keep_md: TRUE
    code_folding: hide
    collapsed: no
    toc: yes
    toc_float: yes
    self_contained: no
   
---

## Extraction method 
The metabolomics extraction procedure was conducted in the cold room (2°C). The extraction solvent was composed of 40:40:20 Methanol, Acetonitrile and Water with the addition of 0.1% Formic acid. Extraction solvent (1.3 mL) was added to each sample. The samples were vortex and placed at -20°C for twenty minutes to incubate. Then samples were centrifuged for 5 minutes at 16.5 rpm. The supernatant was transferred to a clean 2 mL tube. The pellet in each sample tube was broken up and an additional 0.2 mL of extraction solvent was added. The samples were vortex a second time and placed in -20°C for an additional 20 minutes. The samples were centrifuged again using the sample parameters as stated above and the supernatant from the samples was added to the first collection of supernatant. The supernatant from the extracted sampled were dried under a stream of nitrogen gas. Once dry the samples were reconstituted in 200 uL of water. 

## Metabolomic LC/MS method
Samples were separated on a Phenomonex Synergi Hydro RP, 2.5 um, 100 mm x 2.0 mm column.The column was kept at 25˚C. The mobile phases used to elute the metabolites were (A) 97:3 Water to Methanol with 11 mM Tributylamine and 15 mM Acetic acid and (B) 100% Methanol. The multi-step gradient found in table 1 was used for the 25 minute method with a flow rate of 0.2 mL/minute. Thermo Scientific Exactive™ Plus Orbitrap Mass Spectrometer used an electrospray ionization (ESI) probe operating in negative mode. The scan range was 72-1000 m/z.

Table 1: Metabolomics UHPLC solvent gradient
Time (minutes)	Mobile Phase A	Mobile Phase B,
0	100%	0%
5	80%	20%
13	45%	55%
15.5	5%	95%
19	100%	0%
25	100%	%

## Metabolite data analysis 
The peak area from the metabolites signal intensity was picked using the MAVEN software. Metabolite intensity counts were normalized by sample weight. Statistical analysis such as average, standard deviation, standard deviation error and coefficient of variation were performed for each sample group.
